### ISSUE TITLE
get_validator takes too much time

### ISSUE THREAD

**Issue by sjiekak** [p1c2u/openapi-core#289]
I benchmarked a validation against a json input of roughly 700k characters, and it seems deepcopy of the checker is the costliest operation

![snakeviz performance validate ](https://user-images.githubusercontent.com/1922047/107801992-12d2eb00-6d61-11eb-8314-29d8ae310ea4.png)

`get_validator` relies on `_get_format_checker`
    
```
    def _get_format_checker(self):
        fc = deepcopy(oas30_format_checker)
        for name, formatter in self.custom_formatters.items():
            fc.checks(name)(formatter.validate)
        return fc
```

The deepcopy of `oas30_format_checker` is where most of the time is spent. Can you help me understand why there is a need for deepcopy ?

**Comment by p1c2u** [comment]
Hi @sjiekak
That's interesting. I wasn't aware of `deepcopy` slowness . This part of code is responsible for creation of format checker and I use `oas30_format_checker` for default formats and add custom ones with `checks` method. You need to get new object not the reference for that otherwise you will end up having custom formats inside default `oas30_format_checker `.
This can be problematic when you have more specs with different custom formats or when you use `oas30_format_checker ` somewhere else. 
I'm wondering if shallowed copy would be better here.

**Comment by p1c2u** [comment]
One more thing is you have high number of calls for copy which can be because of many requests.
Solution for that can be keeping reference to custom format checker and reusing it for each request.

**Comment by sjiekak** [comment]
Thanks for the swift reaction!
